// message catalog
var model_all = "test";

var message = {
    "hyun_Korean(internal)": {
    	html_title: "사용설명서",
        title: "표준형 블루링크 내비게이션",
        model: model_all,
        search: "Search",
        keyword: "검색어 입력",
        result: "검색 결과가 없습니다.",
        result_toc: "목차 검색",
        search_short: "검색어가 너무 짧습니다.",
        search_more: "더보기",
        search_less: "숨기기",
        close: "닫기",
        other_link: "영상 메뉴얼",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_English(internal)": {
    	html_title: "User's Manual",
        title: "Standard Blue Link Navigation System",
        model: model_all,
        search: "Search",
        keyword: "Enter search keyword",
        result: "No results found.",
        result_toc: "Table of contents",
        search_short: "Keyword is too short.",
        search_more: "More",
        search_less: "Less",
        close: "Close",
        other_link: "video manual",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
	"hyun_CAN_English(NA)": {
		html_title: "User's Manual",
        title: "Standard Blue Link Navigation System",
        model: model_all,
        search: "Search",
        keyword: "Enter search keyword",
        result: "No results found.",
        result_toc: "Table of contents",
        search_short: "Keyword is too short.",
        search_more: "More",
        search_less: "Less",
        close: "Close",
        other_link: "video manual",
        footer_line1: "COPYRIGHT &copy; KIA MOTORS COPR. ",
        footer_line2: "ALL RIGHTS RESERVED.",
    },
	"hyun_USA_English(NA)": {
		html_title: "User's Manual",
        title: "Standard Blue Link Navigation System",
        model: model_all,
        search: "Search",
        keyword: "Enter search keyword",
        result: "No results found.",
        result_toc: "Table of contents",
        search_short: "Keyword is too short.",
        search_more: "More",
        search_less: "Less",
        close: "Close",
        other_link: "video manual",
        footer_line1: "COPYRIGHT &copy; KIA MOTORS COPR. ",
        footer_line2: "ALL RIGHTS RESERVED.",
    },
   	"hyun_English(ME)": {
   		html_title: "User's Manual",
        title: "Standard Blue Link Navigation System",
        model: model_all,
        search: "Search",
        keyword: "Enter search keyword",
        result: "No results found.",
        result_toc: "Table of contents",
        search_short: "Keyword is too short.",
        search_more: "More",
        search_less: "Less",
        close: "Close",
        other_link: "video manual",
        footer_line1: "COPYRIGHT &copy; KIA MOTORS COPR. ",
        footer_line2: "ALL RIGHTS RESERVED.",
    },
    "hyun_Arabic": {
        title: "دليل المستخدم",
        model: model_all,
        search: "بحث",
        keyword: "إدخال كلمة أساسية للبحث",
        result: "لم يتم العثور على نتائج.",
        result_toc: "جدول المحتويات",
        search_short: "الكلمة الأساسية قصيرة للغاية.",
        search_more: "المزيد",
        search_less: "أقل",
        close: "إغلاق",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Bulgarian": {
        title: "Ръководство на потребителя",
        model: model_all,
        search: "Търсене",
        keyword: "Въведете ключова дума за търсене",
        result: "Не са намерени резултати.",
        result_toc: "Съдържание",
        search_short: "Ключовата дума е твърде къса.",
        search_more: "Още",
        search_less: "По-малко",
        close: "Затваряне",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Croatian": {
        title: "Korisnički priručnik",
        model: model_all,
        search: "Τraži",
        keyword: "Unos ključne riječi za pretragu",
        result: "Nema rezultata.",
        result_toc: "Sadržaj",
        search_short: "Ključna riječ je prekratka.",
        search_more: "Više",
        search_less: "Manje",
        close: "Zatvoriti",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Czech": {
        title: "Uživatelská příručka",
        model: model_all,
        search: "Hledat",
        keyword: "Zadat klíčové slovo pro vyhledávání",
        result: "Nenalezeny žádné výsledky.",
        result_toc: "Obsah",
        search_short: "Klíčové slovo je příliš krátké.",
        search_more: "Další",
        search_less: "Méně",
        close: "Zavřít",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Danish": {
        title: "Brugervejledning",
        model: model_all,
        search: "Søg",
        keyword: "Indtast søgenøgleord",
        result: "Ingen resultater blev fundet.",
        result_toc: "Indholdsoversigt",
        search_short: "Nøgleord er for kort.",
        search_more: "Mere",
        search_less: "Mindre",
        close: "Luk",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Dutch": {
        title: "Gebruiksaanwijzing",
        model: model_all,
        search: "Zoeken",
        keyword: "Zoekwoord ingeven",
        result: "Geen resultaten gevonden.",
        result_toc: "Inhoudsopgave",
        search_short: "Zoekwoord is te kort.",
        search_more: "Meer",
        search_less: "Minder",
        close: "Sluiten",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Estonian": {
        title: "Kasutusjuhend",
        model: model_all,
        search: "Otsi",
        keyword: "Sisestage otsingusõna",
        result: "Vasteid ei leitud.",
        result_toc: "Sisukord",
        search_short: "Otsingusõna on liiga lühike.",
        search_more: "Veel",
        search_less: "Vähem",
        close: "Sulgege",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Farsi": {
        title: "دفترچه راهنمای کاربر",
        model: model_all,
        search: "جستجو",
        keyword: "کلیدواژه برای جستجو را وارد کنید",
        result: "نتیجه ای یافت نشد.",
        result_toc: "فهرست مطالب",
        search_short: "کلیدواژه بیش از اندازه کوتاه است.",
        search_more: "بیشتر",
        search_less: "کمتر",
        close: "بستن",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Finnish": {
        title: "Käyttöopas",
        model: model_all,
        search: "Etsi",
        keyword: "Anna hakusana",
        result: "Tuloksia ei löytynyt.",
        result_toc: "Sisällysluettelo",
        search_short: "Hakusana on liian lyhyt.",
        search_more: "Lisää",
        search_less: "Vähemmän",
        close: "Sulje",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_French": {
        title: "Mode d’emploi",
        model: model_all,
        search: "Rech.",
        keyword: "Saisir le mot clé de recherche",
        result: "Aucun résultat trouvé.",
        result_toc: "Table des matières",
        search_short: "Le mot clé est trop court.",
        search_more: "Plus",
        search_less: "Moins",
        close: "Fermer",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },

    "hyun_German": {
        title: "Benutzerhandbuch",
        model: model_all,
        search: "Suche",
        keyword: "Suchbegriff eingeben",
        result: "Keine Ergebnisse.",
        result_toc: "Inhaltsverzeichnis",
        search_short: "Der Suchbegriff ist zu kurz.",
        search_more: "Optionen",
        search_less: "Weniger",
        close: "Schließen",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Greek": {
        title: "Εγχειρίδιο χρήσης",
        model: model_all,
        search: "Αναζήτ.",
        keyword: "Εισαγωγή λέξης αναζήτησης",
        result: "Δεν βρέθηκαν αποτελέσματα.",
        result_toc: "Πίνακας περιεχομένων",
        search_short: "Η λέξη κλειδί είναι πολύ μικρή.",
        search_more: "Περισσότ.",
        search_less: "Λιγότερα",
        close: "Κλείσιμο",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_HongKong": {
        title: "用戶手冊",
        model: model_all,
        search: "搜尋",
        keyword: "輸入搜尋關鍵字",
        result: "找不到結果。",
        expand: "展開",
        collapse: "收起",
        result_toc: "目錄",
        search_short: "關鍵字太短。",
        search_more: "更多",
        search_less: "更少",
        close: "關閉",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Hungarian": {
        title: "Felhasználói kézikönyv",
        model: model_all,
        search: "Keres",
        keyword: "Írjon be keresési kulcsszót",
        result: "Nincs találat.",
        result_toc: "Tartalomjegyzék",
        search_short: "A kulcsszó túl rövid.",
        search_more: "Egyebek",
        search_less: "Egyebek nélkül",
        close: "Bezárás",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Indonesian": {
        title: "Petunjuk Penggunaan",
        model: model_all,
        search: "Mencari",
        keyword: "Masukkan kata kunci pencarian",
        result: "Hasil tidak ditemukan.",
        result_toc: "Daftar isi",
        search_short: "Kata kunci terlalu pendek.",
        search_more: "Lainnya",
        search_less: "Lebih sedikit",
        close: "Tutup",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Italian": {
        title: "Manuale dell'utente",
        model: model_all,
        search: "Cerca",
        keyword: "Inserite la parola chiave da cercare",
        result: "Nessun risultato trovato.",
        result_toc: "Sommario",
        search_short: "La parola chiave è troppo breve.",
        search_more: "Altro",
        search_less: "Meno",
        close: "Chiudi",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Kazakh": {
        title: "Пайдаланушы нұсқаулығы",
        model: model_all,
        search: "Іздеу",
        keyword: "Іздеу кілтсөзін енгізу",
        result: "Нәтижелер табылмады.",
        result_toc: "Мазмұны",
        search_short: "Кілтсөз тым қысқа.",
        search_more: "Қосымша",
        search_less: "Аз",
        close: "Жабу",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Latvian": {
        title: "Lietotāja rokasgrāmata",
        model: model_all,
        search: "Meklēt",
        keyword: "Ievadiet atslēgvārdu meklēšanai",
        result: "Nekas netika atrasts.",
        result_toc: "Saturs",
        search_short: "Atslēgvārds ir pārāk īss.",
        search_more: "Citi",
        search_less: "Mazāk",
        close: "Aizvērt",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Lithuanian": {
        title: "Naudotojo vadovas",
        model: model_all,
        search: "Ieškoti",
        keyword: "Įvesti paieškos raktažodį",
        result: "Rezultatų nerasta.",
        result_toc: "Turinys",
        search_short: "Raktažodis per trumpas.",
        search_more: "Daugiau",
        search_less: "Mažiau",
        close: "Uždaryti",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Macedonian": {
        title: "Упатство за корисникот",
        model: model_all,
        search: "Пребар.",
        keyword: "Внесете клучен збор за пребарување",
        result: "Нема резултати.",
        result_toc: "Содржина",
        search_short: "Клучниот збор е премногу мал.",
        search_more: "Повеќе",
        search_less: "Помалку",
        close: "Затвори",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Norwegian": {
        title: "Brukerhåndbok",
        model: model_all,
        search: "Søk",
        keyword: "Angi søkeord",
        result: "Ingen resultater funnet.",
        result_toc: "Innholdsfortegnelse",
        search_short: "Søkeordet er for kort.",
        search_more: "Mer",
        search_less: "Mindre",
        close: "Lukk",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Polish": {
        title: "Instrukcja obsługi",
        model: model_all,
        search: "Szukaj",
        keyword: "Wprowadź słowo kluczowe wyszukiwania",
        result: "Nie znaleziono wyników.",
        result_toc: "Spis treści",
        search_short: "Słowo kluczowe jest zbyt krótkie.",
        search_more: "Więcej",
        search_less: "Mniej",
        close: "Zamknij",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Portuguese": {
        title: "Manual do utilizador",
        model: model_all,
        search: "Procurar",
        keyword: "Insira palavra-chave a procurar",
        result: "Sem resultados.",
        result_toc: "Índice remissivo",
        search_short: "A palavra-chave é muito pequena.",
        search_more: "Mais",
        search_less: "Menos",
        close: "Fechar",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },

    "hyun_PRC Chinese": {
        title: "使用说明书",
        model: model_all,
        search: "搜索",
        keyword: "输入搜索关键字",
        result: "未找到结果。",
        result_toc: "目录",
        search_short: "关键字过短。",
        search_more: "更多",
        search_less: "更少",
        close: "关闭",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Romanian": {
        title: "Manualul utilizatorului",
        model: model_all,
        search: "Căutare",
        keyword: "Introduceţi cuvânt cheie de căutare",
        result: "Niciun rezultat găsit.",
        result_toc: "Cuprins",
        search_short: "Cuvântul cheie este prea scurt.",
        search_more: "Mai multe",
        search_less: "Mai puţine",
        close: "Închidere",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Russian": {
        title: "Руководство пользователя",
        model: model_all,
        search: "Поиск",
        keyword: "Введите ключевое слово для поиска",
        result: "Результатов не найдено.",
        result_toc: "Содержание",
        search_short: "Ключевое слово слишком короткое.",
        search_more: "Опции",
        search_less: "Меньше",
        close: "Закрыть",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Serbian": {
        title: "Uputstvo za upotrebu",
        model: model_all,
        search: "Traži",
        keyword: "Unesite ključnu reč pretrage",
        result: "Nema pronađenih rezultata.",
        result_toc: "Sadržaj",
        search_short: "Ključna reč je prekratka.",
        search_more: "Još",
        search_less: "Manje",
        close: "Zatvori",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Singapore Chinese": {
        title: "使用说明书",
        model: model_all,
        search: "搜索",
        keyword: "输入搜索关键字",
        result: "未找到结果。",
        result_toc: "目录",
        search_short: "关键字太短。",
        search_more: "更多",
        search_less: "更少",
        close: "关闭",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Slovak": {
        title: "Používateľská príručka",
        model: model_all,
        search: "Hľadať",
        keyword: "Zadajte kľúčové slová na vyhľadanie",
        result: "Neboli nájdené žiadne výsledky.",
        result_toc: "Obsah",
        search_short: "Kľúčové slovo je príliš krátke.",
        search_more: "Ďalšie",
        search_less: "Menej",
        close: "Zatvoriť",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Slovenian": {
        title: "Navodila za uporabo",
        model: model_all,
        search: "Iskanje",
        keyword: "Vnesite ključno besedo iskanja",
        result: "Brez rezultatov.",
        result_toc: "Kazalo",
        search_short: "Ključna beseda je prekratka.",
        search_more: "Manj",
        search_less: "Less",
        close: "Zapri",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Spanish": {
        title: "Manual de usuario",
        model: model_all,
        search: "Buscar",
        keyword: "Introduzca palabra clave de búsqueda",
        result: "No se encontraron resultados.",
        result_toc: "Índice",
        search_short: "La palabra clave es demasiado corta.",
        search_more: "Más",
        search_less: "Menos",
        close: "Cerrar",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Spanish_LA": {
        title: "Manual del usuario",
        model: model_all,
        search: "Buscar",
        keyword: "Ingresar palabra clave de búsqueda",
        result: "No se encontraron resultados.",
        result_toc: "Índice",
        search_short: "La palabra clave es demasiado corta.",
        search_more: "Más",
        search_less: "Menos",
        close: "Cerrar",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Swedish": {
        title: "Bruksanvisning",
        model: model_all,
        search: "Sök",
        keyword: "Ange sökord",
        result: "Inga resultat hittades.",
        result_toc: "Innehållsförteckning",
        search_short: "Sökordet är för kort.",
        search_more: "Mer",
        search_less: "Mindre",
        close: "Stäng",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Taiwan": {
        title: "使用手冊",
        model: model_all,
        search: "搜尋",
        keyword: "輸入搜尋關鍵字",
        result: "找不到結果。",
        result_toc: "目錄",
        search_short: "關鍵字過短。",
        search_more: "更多",
        search_less: "較少",
        close: "關閉",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Thai": {
        title: "คู่มือการใช้งาน",
        model: model_all,
        search: "ค้นหา",
        keyword: "ป้อนคำสำคัญในการค้นหา",
        result: "ไม่พบผลลัพธ์",
        result_toc: "สารบัญ",
        search_short: "คำสำคัญสั้นเกินไป",
        search_more: "เพิ่มเติม",
        search_less: "น้อยลง",
        close: "ปิด",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Turkish": {
        title: "Kullanma Kılavuzu<br /><span class='tur_sub_tit'>Cep Telefonu</span>",
        model: model_all,
        search: "Ara",
        keyword: "Aranacak anahtar kelimeyi girin",
        result: "Sonuç bulunamadı.",
        result_toc: "İçindekiler",
        search_short: "Anahtar kelime çok kısa.",
        search_more: "Diğer",
        search_less: "Daha az",
        close: "Kapat",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Ukrainian": {
        title: "Посібник користувача",
        model: model_all,
        search: "Пошук",
        keyword: "Введіть ключове слово пошуку",
        result: "Жодного результату не знайдено.",
        result_toc: "Зміст",
        search_short: "Ключове слово задовге.",
        search_more: "Додатково",
        search_less: "Менше",
        close: "Закрити",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Urdu": {
        title: "صارف گائیڈ",
        model: model_all,
        search: "سرچ",
        keyword: "تلاش کا کلیدی لفظ درج کریں",
        result: "کوئی نتائج نہیں ملے۔",
        result_toc: "مشمولات کا جدول",
        search_short: "کلیدی لفظ بہت مختصر ہے۔",
        search_more: "اور",
        search_less: "کم",
        close: "بند کریں",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Uzbek": {
        title: "Foydalanuvchi qo‘llanmasi",
        model: model_all,
        search: "Qidirish",
        keyword: "Qidirish kalit so‘zini kiriting",
        result: "Natijalar topilmadi.",
        result_toc: "Mundarija",
        search_short: "Kalit so‘z juda qisqa.",
        search_more: "Yana",
        search_less: "Kamroq",
        close: "Yopish",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Vietnamese": {
        title: "Sách hướng dẫn sử dụng",
        model: model_all,
        search: "T.kiếm",
        keyword: "Nhập từ khóa tìm kiếm",
        result: "Không tìm thấy kết quả nào.",
        result_toc: "Mục lục",
        search_short: "Từ khóa quá ngắn.",
        search_more: "Nhiều hơn",
        search_less: "Ít hơn",
        close: "Đóng",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    },
    "hyun_Hebrew": {
        title: "מדריך למשתמש",
        model: model_all,
        search: "חיפוש",
        keyword: "הקלד מילות חיפוש",
        result: "לא נמצאו תוצאות.",
        result_toc: "תוכן העניינים",
        search_short: "מילת חיפוש קצרה מדי.",
        search_more: "עוד",
        search_less: "פחות",
        close: "סגור",
        footer_line1: "Copyright &copy; 2018 Hyundai Motor Company.",
        footer_line2: "All rights reserved.",
    }
};